stages:
  - test

tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.41.1-jammy
  script:
    - npm install ci
    - npm install -D @playwright/test
    - npm ci
    - npx playwright test 
  timeout: 23 hours 59 minutes
  artifacts:
    paths:
      - ./playwright-report/
      - ./Screenshot/
    when: always
    expire_in: 30 days